version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        restart: always
        volumes:
            - ./nginx:/etc/nginx/conf.d/:ro
            - ./delft:/delft/:rw
            - ./certbot/www:/var/www/certbot/:ro
            - ./certbot/conf/:/etc/nginx/ssl/:ro
        links:
            - php
        networks:
            - front
            - backend
    php:
        image: php:7-fpm
        volumes:
            - ./delft:/delft/:rw
        networks:
            - front
            - backend
    certbot:
        image: certbot/certbot:latest
        volumes:
            - ./certbot/www/:/var/www/certbot/:rw
            - ./certbot/conf/:/etc/letsencrypt/:rw
        networks:
            - front
            - backend

networks:
    front:
        name: front
        external: true
    backend: