version: "3"

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./delft:/delft
            - ./nginx:/etc/nginx/conf.d
        links:
            - php
    php:
        image: php:7-fpm
        volumes:
            - ./delft:/delft